import Providers from "./providers";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
            <nav style={{padding: '5px 0'}}>
                <Link href='/'>FrontPage</Link>
                {` `}
                <Link href="/admin-dashboard">Admin Dashboard</Link>
                {` `}
                <Link href="/profile-page">Profile Page</Link>
            </nav>
            {children}
        </Providers>
      </body>
    </html>
  );
}
